# for configuration: https://golangci-lint.run/usage/configuration/

run:
  # increase timeout (specifically for windows, without cache)
  timeout: 3m
  build-tags:
    - mock # for test files

linters:
  enable:
    - godox # checks no BUG/FIXME/TODO
    - forbidigo # arbitrary forbidden patterns
    - gofmt # formatting
    - revive

linters-settings:
  revive:
    severity: error
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-block
      - name: empty-block
        severity: error

  staticcheck:
    checks:
      - "-S1008" # about simplifying conditions https://staticcheck.dev/docs/checks/#S1008

  errcheck:
    exclude-functions:
      # used with defer without error checking, can't do anything if failed
      - (*github.com/schollz/progressbar/v3.ProgressBar).Finish

  forbidigo:
    # for more options see https://golangci-lint.run/usage/linters/#forbidigo
    forbid:
      - p: time.Sleep
        msg: "`time.Sleep` not allowed"
